services:
  login:
    image: node:18
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      APPLICATION_PORT: ${APPLICATION_PORT}
      API_KEY: ${API_KEY}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_KEY: ${DATABASE_KEY}
      DATABASE_USER: ${DATABASE_USER}
      USER_API_HOST: ${USER_API_HOST}
      USER_API_KEY: ${USER_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
