services:
  spa:
    image: node:18
    container_name: sap_prefeitura
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.03'
          memory: 256M
        reservations:
          memory: 128M
    environment:
      NODE_ENV: ${NODE_ENV}
      APPLICATION_PORT: 3000
      API_KEY: ${API_KEY}
      DATABASE_URL: ${DATABASE_URL}

      USER_API_HOST: ${USER_API_HOST}
      USER_API_KEY: ${USER_API_KEY}

      SECRET_KEY: ${SECRET_KEY}
      FT_APP_API_HOST: ${FT_APP_API_HOST}
      FT_APP_API_KEY: ${FT_APP_API_KEY}

      MAIL_ADRESS: ${MAIL_ADRESS}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
    ports:
      - 3000:${APPLICATION_PORT}
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
