services:
  login:
    image: node:18
    container_name: app_prefeitura_login
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      APPLICATION_PORT: ${APPLICATION_PORT}
      API_KEY: ${API_KEY}
      DATABASE_URL: ${DATABASE_URL}

      USER_API_HOST: ${USER_API_HOST}
      USER_API_KEY: ${USER_API_KEY}

      SECRET_KEY: ${SECRET_KEY}
    ports:
      - 3000
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
